title: Freifunk Cambridge
description: Free WiFi networks in and around Cambridge 
remote_theme: BDHU/minimalist
plugins:
- jekyll-remote-theme

sidebar:
  - name: Get involved
    link: https://cambridge.freifunk.net/get-involved
  - name: Existing Free WiFi networks
   link: https://cambridge.freifunk.net/existing 
  - name: About
    link: https://cambridge.freifunk.net/about
  - name: Mailing list
    link: https://lists.freifunk.net/mailman/listinfo/cambridge-freifunk.net