title: Freifunk Cambridge
description: A free, de-centralised network in Cambridge and surrounding areas 
remote_theme: BDHU/minimalist
plugins:
- jekyll-remote-theme

sidebar:
  - name: Get involved
    link: https://cambridge.freifunk.net/get-involved
  - name: Existing Free WiFi networks
    link: https://cambridge.freifunk.net/existing 
  - name: Mailing list
    link: https://lists.freifunk.net/mailman/listinfo/cambridge-freifunk.net